name: Issue Closed or Commented

on:
  issues:
    types: [closed]
  issue_comment:
    types: [created]
jobs:
  call_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Call Webhook
        env:
          WEBHOOK_URL: ${{ vars.WEBHOOK_URL }}
        run: curl ${{ vars.WEBHOOK_URL }} -vvv
